# Generated by Django 3.2.5 on 2021-08-30 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_auto_20210830_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pybo.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.TextField(choices=[('정보', '정보게시판'), ('질문', '질문게시판'), ('인사', '인사게시판')], default=''),
        ),
    ]
